# Generated by Django 3.2.6 on 2021-09-23 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_pet_pro_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
