# Generated by Django 3.2.6 on 2021-09-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_pet_pro_app', '0002_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
