# Generated by Django 3.2.6 on 2021-10-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_pet_pro_app', '0005_changed_cartitem_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=300, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
