# Generated by Django 3.2.6 on 2021-10-29 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_pet_pro_app', '0006_added_messagebox_date_unique'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagebox',
            options={'ordering': ('-date_added',), 'verbose_name_plural': 'Message Boxes'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
