# Generated by Django 3.2.6 on 2021-11-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('power_pet_pro_app', '0007_unique_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_statement', models.TextField(max_length=500, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mission Statements',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='MissionStatementTopics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=300, unique=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mission Statement Topics',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='MissionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_topic_details', models.TextField(max_length=300)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('mission_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_pet_pro_app.missionstatementtopics')),
            ],
            options={
                'verbose_name_plural': 'Mission Statement Topic Details',
                'ordering': ('-date_added',),
            },
        ),
    ]
