# Generated by Django 3.2.6 on 2021-11-05 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_pet_pro_app', '0008_mission_statement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missionstatementtopics',
            options={'verbose_name_plural': 'Mission Statement Topics'},
        ),
        migrations.AddField(
            model_name='missionstatementtopics',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='missiondetails',
            name='mission_topic_details',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='missionstatement',
            name='main_statement',
            field=models.TextField(max_length=800, unique=True),
        ),
    ]
