# Generated by Django 3.2.6 on 2021-11-19 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_pet_pro_app', '0009_added_mission_topic_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missiondetails',
            name='mission_topic_details',
            field=models.TextField(max_length=800, unique=True),
        ),
    ]
