# Generated by Django 3.2.6 on 2021-12-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_pet_pro_app', '0010_unique_mission_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
