# Generated by Django 3.2.6 on 2022-04-05 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('power_pet_pro_app', '0012_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackanswers',
            options={'verbose_name_plural': 'Answers'},
        ),
        migrations.AlterModelOptions(
            name='feedbackquestions',
            options={'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterField(
            model_name='feedbackanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_pet_pro_app.feedbackquestions'),
        ),
    ]
